### ISSUE TITLE
Cannot find WhatsDump AVD

### ISSUE THREAD

**Issue by Acimaz** [MarcoG3/WhatsDump#23]
After running --install-sdk successfully i ran into this issue while running whatsdump with --wa-phone and --wa-verfiy sms attributes.

The whole error message is like this:

`[ERROR] Cannot find WhatsDump AVD; install Android SDK and emulator packages wit
h --install-sdk`

EDIT: i was using the .exe for windows

**Comment by MarcoG3** [comment]
Let's continue this on issue #24

**Comment by Acimaz** [comment]
These are 2 seperate bugs.
This one happens with the .exe and #24 happens with the python project using a virtual environment

**Comment by phwi** [comment]
I have the same problem

`[ERROR] Cannot find WhatsDump AVD; install Android SDK and emulator packages wit h --install-sdk`

It occurs if I run whatsdump with --wa-phone and --wa-verfiy sms but it also occurs when running the *.exe ... or if I just run "whaatsdump.py"...

Can someone assist me because I just don't understand the problem/soluation, even though I've read through the issues section for hours now...

Is there even a solution?

PS: I had run 
`whatsdump.py --install-sdk`
before, which first runs through updates until 100% and then says accepting SDK licenses and then fetch remote repository and then computing updates and finally it gets "stuck" at 
`All SDK package licenses accepted`

And I plugged in my phone in USB-debugging mode...
