### ISSUE TITLE
TypeError: adb_root() missing 1 required positional argument: 'serialn'

### ISSUE THREAD

**Issue by cachuzo** [MarcoG3/WhatsDump#66]
Hello Guys,

I did a checkout of Tkd-Alex's fork, commit cfa9be737d213b50b80f6ba28868f5fa3703dd7d.

When I tried to execute it, I have got this error: TypeError: adb_root() missing 1 required positional argument: 'serialn'
Attached is the full log of messages displayed.

[error.txt](https://github.com/MarcoG3/WhatsDump/files/6794743/error.txt)

Thanks a lot!

**Comment by Vetalb60** [comment]
Hello,cachuzo.

Set the value 'serial' as None by default.

    def adb_root(self, serialn = None):
        return self._run_cmd_adb("-s {} root".format(serialn)).returncode == 0

**Comment by Vetalb60** [comment]
https://github.com/MarcoG3/WhatsDump/issues/66  От: cachuzoОтправлено: 10 июля 2021 г. в 8:51Кому: MarcoG3/WhatsDumpКопия: SubscribedТема: [MarcoG3/WhatsDump] TypeError: adb_root() missing 1 required positional argument: 'serialn' (#66) Hello Guys,I did a checkout of Tkd-Alex's fork, commit cfa9be7.When I tried to execute it, I have got this error: TypeError: adb_root() missing 1 required positional argument: 'serialn'Attached is the full log of messages displayed.error.txtThanks a lot!—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by cachuzo** [comment]
Thanks, Issue solved
